stages:
  - build


build-docker:
  stage: build
  image: docker:20.10.8
  services:
    - docker:20.10.8-dind
  script:
    - echo $CI_REGISTRY
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY/serve-segmentation/server:latest || true
    - docker build --cache-from $CI_REGISTRY/serve-segmentation/server:latest -t $CI_REGISTRY/serve-segmentation/server:latest -t $CI_REGISTRY/serve-segmentation/server:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY/serve-segmentation/server:$CI_COMMIT_BRANCH -f docker/Dockerfile .
    - docker push $CI_REGISTRY/serve-segmentation/server:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY/serve-segmentation/server:$CI_COMMIT_BRANCH
    - if [ "$CI_COMMIT_BRANCH" = "master" ]; then docker push $CI_REGISTRY/serve-segmentation/server:latest; fi
